---
title: "lab03"
author: "lucas"
date: "2026-08-31"
output: html_document
---
```{r}
library(readr)
library(dplyr)
library(tidyr)
library(purrr)
library(leaflet)
```

```{r}
airlines <- read_csv("airlines.csv", show_col_types = FALSE)

airports <- read_csv(
  "airports.csv",
  col_select = c(IATA_CODE, CITY, STATE, LATITUDE, LONGITUDE),
  show_col_types = FALSE
)
```

```{r}
processar_bloco <- function(bloco, pos) {
  bloco %>%
    select(DESTINATION_AIRPORT, ARRIVAL_DELAY) %>%
    filter(!grepl("^1", DESTINATION_AIRPORT)) %>%
    drop_na() %>%
    group_by(DESTINATION_AIRPORT) %>%
    summarise(
      soma_atraso = sum(ARRIVAL_DELAY),
      n_voos = n(),
      .groups = "drop"
    )
}

estatisticas_blocos <- read_csv_chunked(
  "flights.csv",
  callback = DataFrameCallback$new(processar_bloco),
  chunk_size = 1000000,
  progress = FALSE,
  show_col_types = FALSE
)

flights <- estatisticas_blocos %>%
  group_by(DESTINATION_AIRPORT) %>%
  summarise(
    soma_atraso = sum(soma_atraso),
    n_voos = sum(n_voos),
    MEDIA_ATRASO = soma_atraso / n_voos,
    .groups = "drop"
  ) %>%
  select(DESTINATION_AIRPORT, MEDIA_ATRASO)
```


```{r}
aeroportos_ausentes <- flights %>%
  anti_join(airports, by = c("DESTINATION_AIRPORT" = "IATA_CODE"))

print(aeroportos_ausentes)

flights <- flights %>%
  inner_join(airports, by = c("DESTINATION_AIRPORT" = "IATA_CODE"))
```

```{r}
aeroportos_por_estado <- airports %>%
  count(STATE, name = "QTD_AEROPORTOS") %>%
  arrange(desc(QTD_AEROPORTOS))

print(aeroportos_por_estado)
```

```{r}
this <- leaflet(flights) %>%
  addTiles() %>%
  addCircleMarkers(
    lng = ~LONGITUDE,
    lat = ~LATITUDE,
    popup = ~paste0(
      "<b>Aeroporto:</b> ", DESTINATION_AIRPORT, "<br>",
      "<b>Cidade/UF:</b> ", CITY, "-", STATE, "<br>",
      "<b>Atraso Médio:</b> ", round(MEDIA_ATRASO, 2), " min"
    ),
    radius = ~pmax(3, pmin(MEDIA_ATRASO, 15)),
    stroke = FALSE,
    fillOpacity = 0.6
  )

this
```


```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

